/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CoreServices_CONSTANTS_H
#define CoreServices_CONSTANTS_H

#include "CoreServices_types.h"

namespace com { namespace kaisquare { namespace core { namespace thrift {

class CoreServicesConstants {
 public:
  CoreServicesConstants();

};

extern const CoreServicesConstants g_CoreServices_constants;

}}}} // namespace

#endif
