/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CoreServices_constants.h"

namespace com { namespace kaisquare { namespace core { namespace thrift {

const CoreServicesConstants g_CoreServices_constants;

CoreServicesConstants::CoreServicesConstants() {
}

}}}} // namespace

