/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EventStructures_CONSTANTS_H
#define EventStructures_CONSTANTS_H

#include "EventStructures_types.h"

namespace com { namespace kaisquare { namespace events { namespace thrift {

class EventStructuresConstants {
 public:
  EventStructuresConstants();

};

extern const EventStructuresConstants g_EventStructures_constants;

}}}} // namespace

#endif
