/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "EventStructures_constants.h"

namespace com { namespace kaisquare { namespace events { namespace thrift {

const EventStructuresConstants g_EventStructures_constants;

EventStructuresConstants::EventStructuresConstants() {
}

}}}} // namespace

