// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "IndoorLocationService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::com::kaisquare::core::thrift;

class IndoorLocationServiceHandler : virtual public IndoorLocationServiceIf {
 public:
  IndoorLocationServiceHandler() {
    // Your initialization goes here
  }

  void getMaps(std::vector<IndoorMapInfo> & _return, const std::string& deviceId) {
    // Your implementation goes here
    printf("getMaps\n");
  }

  void getTags(std::vector<TagInfo> & _return, const std::string& deviceId) {
    // Your implementation goes here
    printf("getTags\n");
  }

  void getTagLocation(std::vector<IndoorLocationInfo> & _return, const std::string& deviceId, const std::string& tagId, const std::string& startTimestamp, const std::string& endTimestamp) {
    // Your implementation goes here
    printf("getTagLocation\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<IndoorLocationServiceHandler> handler(new IndoorLocationServiceHandler());
  shared_ptr<TProcessor> processor(new IndoorLocationServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

